### ISSUE TITLE
Почти готово

### ISSUE THREAD

**Issue by lmilunovic** [Ladislav92/Uniq-variant-10-Politeh-Java-project#2]
Переделал что надо было переделать. Надеюсь что всё хорошо сейчас. Тоже, думаю что было прикольно добавить интерфейс IProcessor и имплементировать его. Написал комментариев для моих методов. KVPair<T> имеет новое називание - EntryPair<T>, просто думаю что лучше выглядит.

Прошу Вас смотреть моя изменения.

Тоже, если сегодня не успею, не будет проблем если напишу тесты завтра?

И, есть вопрос в связи с третьим проектом:

Профессор сказал что мы можем выбрат которое приложение делаем. Если так, я бы хотел делать что-то с Spring фреймворком, на пример Chat приложение и наверно Doodle Board с ним (если времени за сделать Doodle Board). Если у Вас лучше предложение для начать учится Spring фреймворке и сетевом программированию, я рад принять его.

**Comment by maximpetrov** [comment]
Меня всё устраивает, есть только небольших замечания:
1. В `processAndOutput` Вы теряете последнюю строку файла.
1. Заставлять пользователя сверять результаты выполнения теста с ожидаемыми не очень хорошо: это и трудоёмко делать каждый раз, и нет никакой гарантии, что Вы не пропустите ошибку. Будет лучше, если тесты сами будут сверять результаты.

**Comment by maximpetrov** [comment]
По поводу третьего задания: я не против Вашего варианта, давайте обсудим детали в четверг на занятии.

**Comment by lmilunovic** [comment]
Поправил ошибку в `processAndOutput`. 
Ещё делаю тесты, было маленких проблем с тесторованием Singleton класса, не знал что так трудно тестировать их. Сегодня наверно всё сделаю.

Есть ещё вопрос. Я понял что я не выключил мой Input и Output stream. 
Лучше выключить их в методам которые их пользуют или написать метод `closeIO` который нужно вызвать когда работа завершена и который выбрасывает исключение если они `null`?

**Comment by maximpetrov** [comment]
Отдельный метод `closeIO` будет больше подходить к общему стилю Вашей программы.

**Comment by lmilunovic** [comment]
Удалось написать тесты. Надеюсь что всё хорошо. На месте `closeIO` сделал `destroy`. Toже, методы 
 `output`, `processAndOutput` и `process` выбрасывают `IllegalStateException` если вход/выход закрыть.

**Comment by maximpetrov** [comment]
Да, теперь всё хорошо.
